name: another_background_location
description: Fork of background_location. A Flutter plugin to get location updates in the background for both Android and iOS.
version: 0.8.1
homepage: https://github.com/juliansteenbakker/another_background_location
repository: https://github.com/juliansteenbakker/another_background_location

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  #test: ^1.16.8
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.background_location
        pluginClass: BackgroundLocationPlugin
      ios:
        pluginClass: BackgroundLocationPlugin
