name: another_background_location
description: Fork of background_location. A Flutter plugin to get location updates in the background for both Android and iOS.
version: 1.0.0
homepage: https://github.com/juliansteenbakker/another_background_location
repository: https://github.com/juliansteenbakker/another_background_location

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.another_background_location
        pluginClass: BackgroundLocationPlugin
      ios:
        pluginClass: BackgroundLocationPlugin
